### ISSUE TITLE
Ensure multiple charts can be downloaded concurrently

### ISSUE THREAD

**Issue by object88** [object88/tugboat#10]
The chart cache has a course-grained lock that only allows a single chart to be downloaded at once.  Improve the cache mechanism so that there can be simultaneous downloads, while still ensuring that a _particular_ chart can't downloaded concurrently.

**Comment by provPaulBrousseau** [comment]
Out of scope; project no longer directly uses helm or a chart cache.

**Comment by object88** [comment]
Out of scope; `tugboat` no longer directly uses helm or manages a cache of charts or repositories.
